# Generated by Django 5.0 on 2023-12-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="img/")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("pnum", models.DecimalField(decimal_places=2, max_digits=10)),
                ("job_role", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
