# Generated by Django 4.2.7 on 2023-12-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pnum',
            field=models.CharField(max_length=15),
        ),
    ]
